from typing import Protocol


class CachePort(Protocol):
    async def get(self, key: str) -> str | None: ...

    async def set(self, key: str, value: str, *, ttl_seconds: int | None = None) -> None: ...

    async def delete(self, key: str) -> None: ...

    async def acquire_lock(self, key: str, *, ttl_seconds: int) -> bool: ...

    async def release_lock(self, key: str) -> None: ...
